# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

images:
- 'asia.gcr.io/${PROJECT_ID}/runtime:latest'
timeout: '21600s'
steps:
- id: 'pull.packages'
  name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-d'
  - '-r'
  - 'gs://${PROJECT_ID}-portage/packages'
  - '/usr/portage/packages'
  volumes:
  - name: 'packages'
    path: '/usr/portage/packages'

- id: 'emerge'
  name: 'gentoo/stage3-amd64-nomultilib'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -eu
    mkdir -p /usr/local
    rsync -a ./ /usr/local/fukan-overlay/
    mkdir -p /etc/portage/repos.conf
    cat >> /etc/portage/repos.conf/fukan-overlay.conf <<EOM
    [fukan-overlay]
    auto-sync = no
    location = /usr/local/fukan-overlay
    EOM
    cat >> /etc/portage/make.conf <<EOM
    MAKEOPTS="-j2"
    EOM
    emerge-webrsync
    emerge --sync --quiet
    mkdir -p /usr/portage/distfiles
    chown root:portage /usr/portage/distfiles
    chmod 775 /usr/portage/distfiles
    eselect profile set fukan-overlay:default/linux/amd64/no-multilib
    PACKAGES="
      dev-python/pip
      virtual/fukan"
    emerge --buildpkg --usepkg --with-bdeps=y --onlydeps --newuse --deep \
      --rebuild-if-new-ver --quiet $${PACKAGES}
    mkdir -p ./build
    chmod +x ./install_stage3.sh
    ./install_stage3.sh ./build
    emerge --root=./build --root-deps=rdeps --quiet --oneshot \
      dev-libs/openssl net-misc/openssh  # NOTE: https://bugs.gentoo.org/531540
    emerge --buildpkg --usepkg --newuse --deep --rebuild-if-new-ver \
      --root=./build --root-deps=rdeps --quiet $${PACKAGES}
  volumes:
  - name: 'packages'
    path: '/usr/portage/packages'

- id: 'push.packages'
  name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-d'
  - '-r'
  - '/usr/portage/packages'
  - 'gs://${PROJECT_ID}-portage/packages'
  volumes:
  - name: 'packages'
    path: '/usr/portage/packages'
  waitFor: ['emerge']

- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--no-cache'
  - '--tag=asia.gcr.io/${PROJECT_ID}/runtime:latest'
  - '.'
  waitFor: ['emerge']
