# Run locally:
#   $ cloud-build-local --dryrun=false .
#
# Run on gcloud:
#   $ gcloud builds submit .

substitutions:
  _PORTAGE_DATE: '20200303'

images:
- 'asia.gcr.io/${PROJECT_ID}/runtime:latest'
- 'asia.gcr.io/${PROJECT_ID}/runtime:${_PORTAGE_DATE}'

timeout: '21600s'  # 6 hours

options:
  volumes:
  - name: 'binpkgs'
    path: '/var/cache/binpkgs'

steps:
- id: 'pull.packages'
  name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-d'
  - '-r'
  - 'gs://${PROJECT_ID}-portage/packages'
  - '/var/cache/binpkgs'

- id: 'emerge'
  name: 'gentoo/stage3-amd64-nomultilib'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -eu
    mkdir -p /usr/local
    rsync -a ./ /usr/local/fukan-overlay/
    mkdir -p /etc/portage/repos.conf
    cat >> /etc/portage/repos.conf/fukan-overlay.conf <<EOM
    [fukan-overlay]
    auto-sync = no
    location = /usr/local/fukan-overlay
    EOM
    cat >> /etc/portage/make.conf <<EOM
    FEATURES="userfetch"
    MAKEOPTS="-j2"
    PYTHON_TARGETS="python3_6"
    EOM
    # Retry emerge-webrsync three times on failure.
    emerge-webrsync --revert=${_PORTAGE_DATE} \
      || emerge-webrsync --revert=${_PORTAGE_DATE} \
      || emerge-webrsync --revert=${_PORTAGE_DATE}
    eselect profile set fukan-overlay:default/linux/amd64/no-multilib
    PACKAGES="
      dev-python/pip
      virtual/fukan"
    emerge --quiet \
      --buildpkg --usepkg --rebuild-if-new-ver \
      --with-bdeps=y --onlydeps --newuse --deep \
      $${PACKAGES}
    mkdir -p ./build
    chmod +x ./install_stage3.sh
    ./install_stage3.sh ./build
    emerge --root=./build --quiet \
      --root-deps=rdeps --oneshot \
      dev-libs/openssl net-misc/openssh  # NOTE: https://bugs.gentoo.org/531540
    emerge --root=./build --quiet \
      --buildpkg --usepkg --rebuild-if-new-ver \
      --root-deps=rdeps --newuse --deep \
      $${PACKAGES}
    emerge --quiet \
      --buildpkg --usepkg \
      app-portage/gentoolkit
    eclean -dq -t 3w packages

- id: 'push.packages'
  name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-d'
  - '-r'
  - '/var/cache/binpkgs'
  - 'gs://${PROJECT_ID}-portage/packages'
  waitFor: ['emerge']

- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--no-cache'
  - '--tag=asia.gcr.io/${PROJECT_ID}/runtime:${_PORTAGE_DATE}'
  - '.'
  waitFor: ['emerge']

- id: 'tag'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'asia.gcr.io/${PROJECT_ID}/runtime:${_PORTAGE_DATE}'
  - 'asia.gcr.io/${PROJECT_ID}/runtime:latest'
  waitFor: ['build']
